spring:
  application:
    name: rinko-channel-qq
  config:
    import:
      - optional:nacos:application-dev.yml
      - optional:nacos:rinko-channel-qq-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:18848}
        namespace: ${NACOS_NAMESPACE:rinko}
        group: anchorage
        username: nacos
        password: isincere.
      config:
        server-addr: ${NACOS_SERVER:127.0.0.1:18848}
        namespace: ${NACOS_NAMESPACE:rinko}
        group: anchorage
        username: nacos
        password: isincere.
        file-extension: yml
server:
  port: 8090

rinko:
  channel:
    qq:
      enabled: false
      bot-id: ${QQ_BOT_ID:}
      client-secret: ${QQ_CLIENT_SECRET:}
