spring:
  application:
    name: rinko-auth
  config:
    import:
      - optional:nacos:application-dev.yml
      - optional:nacos:rinko-auth-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:nacos:8848}
        namespace: ${NACOS_NAMESPACE:rinko}
        group: anchorage
        username: nacos
        password: isincere.
      config:
        server-addr: ${NACOS_SERVER:nacos:8848}
        namespace: ${NACOS_NAMESPACE:rinko}
        group: anchorage
        username: nacos
        password: isincere.
        file-extension: yml

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
  api-docs:
    path: /v3/api-docs
    enabled: false
