spring:
  application:
    name: rinko-notify
  config:
    import:
      - optional:nacos:application-dev.yml
      - optional:nacos:rinko-notify-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:18848}
        namespace: ${NACOS_NAMESPACE:rinko}
        group: anchorage
        username: nacos
        password: isincere.
      config:
        server-addr: ${NACOS_SERVER:127.0.0.1:18848}
        namespace: ${NACOS_NAMESPACE:rinko}
        group: anchorage
        username: nacos
        password: isincere.
        file-extension: yml

server:
  port: 8084

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
  api-docs:
    path: /v3/api-docs
    enabled: false
