# rinko-scheduler 调度服务配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/rinko_scheduler?currentSchema=scheduler
    username: postgres
    password: rinko
    druid:
      initial-size: 20
      max-active: 100
      min-idle: 5
      max-wait: 60000
      filter:
        stat:
          enabled: false
          log-slow-sql: false
          slow-sql-millis: 2000
        wall:
          enabled: true
          config:
            multi-statement-allow: false
            none-base-statement-allow: false
  data:
    redis:
      host: redis
      port: 6379
      database: 0
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rinko
    password: anchorage

rinko:
  scheduler:
    quartz:
      thread-pool-size: 10
    jobs:
      auto-startup: true
