# rinko-auth 认证服务配置
server:
  port: 10316

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/rinko_auth
    username: postgres
    password: rinko
    properties:
      currentSchema: auth
  data:
    redis:
      host: redis
      port: 6379
      database: 0
      password: rinko_redis_2024
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rinko
    password: anchorage
rinko:
  auth:
    jwt:
      secret: ${JWT_SECRET:anchorage_rinko}
      access-token-expiration: 900
      refresh-token-expiration: 604800
