spring:
  application:
    name: rinko-channel-wechat
  config:
    import:
      - optional:nacos:application-dev.yml
      - optional:nacos:rinko-channel-wechat-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:18848}
        namespace: ${NACOS_NAMESPACE:rinko}
        group: anchorage
        username: nacos
        password: isincere.
      config:
        server-addr: ${NACOS_SERVER:127.0.0.1:18848}
        namespace: ${NACOS_NAMESPACE:rinko}
        group: anchorage
        username: nacos
        password: isincere.
        file-extension: yml
server:
  port: 8091

rinko:
  channel:
    wechat:
      enabled: false
      app-id: ${WECHAT_APP_ID:}
      app-secret: ${WECHAT_APP_SECRET:}
      token: ${WECHAT_TOKEN:}
      encoding-aes-key: ${WECHAT_AES_KEY:}
