spring:
  application:
    name: rinko-channel-dingtalk
  config:
    import:
      - optional:nacos:application-dev.yml
      - optional:nacos:rinko-channel-dingtalk-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:18848}
        namespace: ${NACOS_NAMESPACE:rinko}
        group: anchorage
        username: nacos
        password: isincere.
      config:
        server-addr: ${NACOS_SERVER:127.0.0.1:18848}
        namespace: ${NACOS_NAMESPACE:rinko}
        group: anchorage
        username: nacos
        password: isincere.
        file-extension: yml
server:
  port: 8092

rinko:
  channel:
    dingtalk:
      enabled: false
      app-key: ${DINGTALK_APP_KEY:}
      app-secret: ${DINGTALK_APP_SECRET:}
      robot-code: ${DINGTALK_ROBOT_CODE:}
